### ISSUE TITLE
Overwrite specific field

### ISSUE THREAD

**Issue by pixelcraftAU** [dlesbre/bibtex-autocomplete#9]
Hi!

I've noticed you have a flag (`-f --force-overwrite`) to enable overwriting existing fields, but I was wondering if it had the functionality to limit it to a specific field so just overwrite existing authors for example?

**Comment by pixelcraftAU** [comment]
Hi again! :) 

I've just tried this method and the force + only complete option doesn't seem to work with 'author'. It runs fine if I use doi, but if I use author it just skips the whole database querying process and writes a new/exact same file. It also works fine if I don't add the only complete flag and just use force but that changes other data I don't want to alter.

**Comment by dlesbre** [comment]
Hi! Thanks for reporting this bug. I uploaded a new version (1.2.1) with a fix for this and also added new arguments `-< --overwrite` / `-W --dont-overwrite` to avoid having to call `btac` twice.

The reason for the bug was there is some logic to bypass unnecessary queries (aka does this API supply any fields I don't have). This logic took the `-c/-C` flags into account, but I forgot to check for the `-f` flag. So in your case it skipped all queries as entries already had an author field.

**Comment by pixelcraftAU** [comment]
Amazing, thank you!!
